medical/admin1/urls.py
from django.contrib import admin
from django.urls import path
from admin1.views import adminindex,userview,sample1,deleteuser,fullrentorder,sellerview,deleteseller,edits,updates,selleredits,sellerupdates,selleradd,productview,deleteitem,deleterent,deletes,fulltransactions
app_name='admin1'
urlpatterns = [
    path('adminindex/', adminindex,name='adminindex'),
    path('', sample1,name='sample1'),
    path('userview', userview,name='userview'),
    # path('adminorders', adminorders,name='adminorders'),
    path('deleteuser', deleteuser,name='deleteuser'),
    path('fullrentorder', fullrentorder,name='fullrentorder'),
    path('sellerview', sellerview,name='sellerview'),
    path('deleteseller', deleteseller,name='deleteseller'),
    path('edituser', edits,name='edituser'),
    path('update', updates, name='updates'),  
    path('editseller', selleredits,name='editseller'),
    path('updateseller', sellerupdates, name='updateseller'),  
    path('selleradd', selleradd, name='selleradd'),  
    path('productview', productview, name='productview'),  
    path('productview', productview, name='productview'),  
    path('deleteitem', deleteitem, name='deleteitem'),  
    path('deleterent', deleterent, name='deleterent'),  
    path('deletes', deletes, name='deletes'),
    path('transactions', fulltransactions, name='transactions'),    

]

medical/main/urls.py
from django.contrib import admin
from django.urls import path
from main.views import index,login1,reg,error,payment,orders,logout1,rentdate,rentorder,rentpayment,specificorders,feedback,search,deleteuserorder,deleteuserrent

app_name='medical'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/',index,name='index'),
    path('', login1,name='userlogin'),
    path('reg/', reg,name='reg'),
    # path('adminindex/', adminindex,name='adminindex'),
    path('error/', error),
    path('payment/', payment,name='payment'),
    path('orders/', orders,name='orders'),
    path('deleteuserorder/', deleteuserorder,name='deleteuserorder'),
    path('deleteuserrent/', deleteuserrent,name='deleteuserrent'),

    path('', logout1,name='logout1'),
    path ('rentdate/',rentdate,name="rentdate"),
    path ('rentorder/',rentorder,name="rentorder"),
    path ('rentpayment/',rentpayment,name="rentpayment"),
    path ('specificorder/',specificorders,name="specificorder"),
    path ('feedback/',feedback,name="feedback"),
    path ('search/',search,name="search"),

]

medical/medical/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('admin1/',include('admin1.urls')),
    path('vendor/',include('vendor.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medical/templates/editproduct.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit User</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">Edit Item</h5>
        </div>
        <div class="card-body">
          <!-- Begin Form -->
          <form action="{% url 'vendor:updateproduct' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for m in secdata %}
            <div class="form-group">
              <label for="userName"> Product Name</label>
              <input type="text" class="form-control" id="userName" value="{{m.pnm}}" name="pname" required>
              <input type="hidden" value="{{m.id}}" name="idno">
            </div>
            <div class="form-group">
              <label for="userMobile">Quantity</label>
              <input type="text" class="form-control" id="userMobile" value="{{m.quantity}}" name="quantiti" required>
            </div>

            <div class="form-group">
              <label for="userMobile">Price</label>
              <input type="text" class="form-control" id="userMobile" value="{{m.prc}}" name="pprice" required>
            </div>

            <div class="form-group">
              <label for="userEmail">Description</label>
              <input type="text" class="form-control" id="userEmail" value="{{m.des}}" name="pdes" required>
            </div>

            <div class="form-group">
              <!-- <label for="userPassword">Seller</label> -->
              <input type="text" class="form-control" id="userPassword" value="{{m.seller}}" name="pseller" hidden>
            </div>

            <div class="form-group">
                <label for="userPassword">Rent Price</label>
                <input type="text" class="form-control" id="userPassword" value="{{m.rentprice}}" name="prent" required>
              </div>
  
            <div class="form-group">
                <label class="form-label" for="customFile">Default file input example</label>
                <input type="file" name="pimage1" class="form-control" id="customFile" />            
            </div>            
  
            <button class="btn btn-primary" type="submit">Update</button>
            {% endfor %}
          </form>
          <!-- End Form -->
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap JS and Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

medical/templates/editseller.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit Seller</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">Edit Seller</h5>
        </div>
        <div class="card-body">
          <!-- Begin Form -->
          <form action="{% url 'admin1:updateseller' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for m in secdatas %}
            <div class="form-group">
              <label for="userName">Name</label>
              <input type="text" class="form-control" id="userName" value="{{m.fnm}}" name="uname" required>
              <input type="hidden" value="{{m.id}}" name="idno">
            </div>

            <div class="form-group">
              <label for="userMobile">Mobile</label>
              <input type="text" class="form-control" id="userMobile" value="{{m.mob}}" name="umobile" required>
            </div>

            <div class="form-group">
              <label for="userEmail">Email</label>
              <input type="text" class="form-control" id="userEmail" value="{{m.eml}}" name="uemail" required>
            </div>

            <div class="form-group">
              <label for="userPassword">Password</label>
              <input type="text" class="form-control" id="userPassword" value="{{m.psw}}" name="upassword" required>
            </div>

            <button class="btn btn-primary" type="submit">Update</button>
            {% endfor %}
          </form>
          <!-- End Form -->
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap JS and Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

medical/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Add Product</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {% if messages %}
    {% for m in messages %}
    <h4>{{m}}</h4>
    {% endfor %}
    {% endif %}
<form action=""method="post">
  {% csrf_token %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">Send Feedback</h5>
        </div>
        <div class="card-body">
          <form>
            <div class="form-group">
              <label for="cardNumber">Subject</label>
              <input type="text" class="form-control" id="cardNumber" placeholder="Enter Product Name" name= "subject"required>
            </div>

            <div class="form-group col-md-6">
              <label for="expiryDate">Type Message</label>
              <textarea class="form-control" id="expiryDate" placeholder="Product Description"name="message" required></textarea>
            </div>

          <button class="btn btn-primary" type="submit">submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</form>
<!-- Bootstrap JS and Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

medical/templates/fullorders.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Item</th>
        <th scope="col">Seller</th>
        <th scope="col">Buyer</th>

      </tr>
    </thead>
    <tbody>
      {% for y in datas %}
  

      <tr>
        <th scope="row">{{y.id}}</th>
        <td id="pname">{{y.opnm}}
        </td>
        <td id="pprice">{{y.oprc}}</td>
        <td id="pdes">{{y.odes}}</td>
        <td id="pseller">{{y.oseller}}</td>
        <td id="pseller">{{y.Buyer}}</td>


        <td><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="/admin1/deletes?idn={{y.id}}">Cancel Order</a></button>
        </td>
      </tr>
      {% endfor %}
        <td><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="{% url 'admin1:adminindex' %}">Home</a></button>

     
    </tbody>
  </table>

medical/templates/manageitems.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Item</th>
        <th scope="col">Seller</th>

      </tr>
    </thead>
    <tbody>
      {% for y in sdatas %}
  

      <tr>
        <th scope="row">{{y.id}}</th>
        <td id="pname">{{y.pnm}}
        </td>
        <td id="pprice">{{y.prc}}</td>
        <td id="pdes">{{y.des}}</td>
        <td id="pseller">{{y.seller}}</td>


        <td><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="/vendor/editproduct?idn={{y.id}}">Edit Item</a></button>
        <td><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="/vendor/deleteselleritem?idn={{y.id}}">Delete Item</a></button>

        </td>
      </tr>
      {% endfor %}
        <td><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="{% url 'vendor:vendorindex' %}">Home</a></button>

     
    </tbody>
  </table>

medical/templates/orders.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Item</th>
        <th scope="col">Seller</th>
        <th scope="col">Buyer</th>

      </tr>
    </thead>
    <tbody>
      {% for y in odatass %}
  

      <tr>
        <th scope="row">{{y.id}}</th>
        <td id="pname">{{y.opnm}}
        </td>
        <td id="pprice">{{y.oprc}}</td>
        <td id="pdes">{{y.odes}}</td>
        <td id="pseller">{{y.oseller}}</td>
        <td id="pseller">{{y.Buyer}}</td>


        <td><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="/deleteuserorder?idn={{y.id}}">Cancel Order</a></button>
        </td>
      </tr>
      {% endfor %}
        <td><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="/index">Home</a></button>

     
    </tbody>
  </table>

medical/templates/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Payment Page</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">Payment Details</h5>
        </div>
        <div class="card-body">
          <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="cardNumber">Name</label>
              <input type="text" class="form-control" id="cardNumber" placeholder="Enter Your Name" name="name" required>
            </div>
            <div class="form-group">
              <label for="cardNumber">House Name</label>
              <input type="text" class="form-control" id="cardNumber" placeholder="Enter House Name" name="hname" required>
            </div>

            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="expiryDate">Street</label>
                <input type="text" class="form-control" id="expiryDate" placeholder="Enter Street" name="street" required>
              </div>
              <div class="form-group col-md-6">
                <label for="cvv">Pincode</label>
                <input type="text" class="form-control" id="cvv" placeholder="Enter Pincode" name="pincode" required>
              </div>
            </div>
            <div class="form-group">
              <label for="nameOnCard">City</label>
              <input type="text" class="form-control" id="nameOnCard" placeholder="Enter City" name="city" required>
            </div>
            <div class="form-group">
              <label for="amount">Mobile Number</label>
              <input type="text" class="form-control" id="amount" placeholder="Enter Mobile Number" name="mob" required>
            </div>
            <button class="btn btn-primary" type="submit">Submit Payment</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap JS and Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

medical/templates/productadd.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Add Product</title>
  <!-- Bootstrap CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<form action=""method="post" enctype="multipart/form-data">
  {% csrf_token %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">Add Product</h5>
        </div>
        <div class="card-body">
          <form>
            <div class="form-group">
              <label for="cardNumber">Product Name</label>
              <input type="text" class="form-control" id="cardNumber" placeholder="Enter Product Name" name= "pname1"required>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="expiryDate">Product price</label>
                <input type="text" class="form-control" id="expiryDate" placeholder="$" name="pprice1" required>
              </div>
              <div class="form-group col-md-6">
                <label for="cvv">Rent Price</label>
                <input type="text" class="form-control" id="cvv" placeholder="$" name="prent1" required>
              </div>
              <div class="form-group col-md-6">
                <label for="cvv">Quantity</label>
                <input type="text" class="form-control" id="cvv" placeholder="Enter Quantity" name="quantity" required>
              </div>

            </div>

            <div class="form-group col-md-6">
              <!-- <label for="expiryDate">Seller</label> -->
              <input type="area" class="form-control" id="expiryDate" placeholder="$" name="pseller1" value="seller1" hidden>
            </div>

            <div class="form-group col-md-6">
              <label for="expiryDate">Description</label>
              <textarea class="form-control" id="expiryDate" placeholder="Product Description"name="pdes1" required></textarea>
            </div>


            <div class="form-group">
              <label class="form-label" for="customFile">Default file input example</label>
              <input type="file" name="pimage1" class="form-control" id="customFile" />            
          </div>            
          <button class="btn btn-primary" type="submit">Add</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</form>
<!-- Bootstrap JS and Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

medical/templates/sellerview.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Mobile Number</th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody>
        {% for m in data %}
      <tr>
        <th scope="row">{{m.id}}</th>
        <td>{{m.fnm}}</td>
        <td>{{m.mob}}</td>
        <td>{{m.eml}}</td>
        <td><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="/admin1/deleteseller?idn={{m.id}}">Remove</a></button></td>
        <td><button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href="/admin1/editseller?idn={{m.id}}">Edit</a></button></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

medical/templates/vendordash.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Vendor Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'medical:logout1' %}">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<style>
    body {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
      background-color: #f0f0f0;
    }
    
    .card-link {
      text-decoration: none; /* Removes underline from links */
    }
  
    .card {
      background-color: #ffffff;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.2);
      transition: all 0.3s ease;
      padding: 20px;
      text-align: center;
      display: block; /* Make the div behave like a block element */
      color: #333; /* Text color */
    }
  
    .card:hover {
      transform: translateY(-5px);
      box-shadow: 0 4px 8px rgba(0,0,0,0.3);
    }
  
    .card h3 {
      margin: 0;
      color: #333;
      font-size: 24px;
    }
  
    .card p {
      color: #666;
    }
  </style>
  </head>
  <body>
  
  <a href="{% url 'vendor:productadd' %}" class="card-link"> <!-- Replace "#" with your link -->
    <div class="card">
      <h3>Add Product</h3>
      <p>Click here to add a new product.</p>
    </div>
  </a>

  <a href="{% url 'vendor:manageitems' %}" class="card-link"> <!-- Replace "#" with your link -->
    <div class="card">
      <h3>Manage Items</h3>
      <p>Click here to Manage Items.</p>
    </div>
  </a>

  <a href="{% url 'vendor:sellerorder' %}" class="card-link"> <!-- Replace "#" with your link -->
    <div class="card">
      <h3>Orders</h3>
      <p>Click here to view Orders.</p>
    </div>
  </a>

  <a href="{% url 'vendor:sellerrent' %}" class="card-link"> <!-- Replace "#" with your link -->
    <div class="card">
      <h3>Rented items</h3>
      <p>Click here to view Rented items.</p>
    </div>
  </a>

  </body>